[tool.poetry]
name = "python05-bis-ex0"
version = "0.1.0"
description = "Dependencies for the sealed laboratory exercise"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pandas = ">=2.2.3,<3.0"
numpy = ">=2.1,<3.0"

[build-system]
requires = ["poetry-core>=1.8.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
